# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Base_LoadThemAll.ui'
#
# Created: Sat Jan 17 22:37:29 2015
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Base_LoadThemAll(object):
    def setupUi(self, Base_LoadThemAll):
        Base_LoadThemAll.setObjectName(_fromUtf8("Base_LoadThemAll"))
        Base_LoadThemAll.resize(375, 347)
        self.gridLayout = QtGui.QGridLayout(Base_LoadThemAll)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(20, 15, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
        self.cboFormats = QtGui.QComboBox(Base_LoadThemAll)
        self.cboFormats.setObjectName(_fromUtf8("cboFormats"))
        self.gridLayout.addWidget(self.cboFormats, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(Base_LoadThemAll)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.txtBaseDir = QtGui.QLineEdit(Base_LoadThemAll)
        self.txtBaseDir.setObjectName(_fromUtf8("txtBaseDir"))
        self.gridLayout.addWidget(self.txtBaseDir, 0, 1, 1, 1)
        self.btnBaseDir = QtGui.QPushButton(Base_LoadThemAll)
        self.btnBaseDir.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/loadthemall/dir.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBaseDir.setIcon(icon)
        self.btnBaseDir.setIconSize(QtCore.QSize(22, 22))
        self.btnBaseDir.setObjectName(_fromUtf8("btnBaseDir"))
        self.gridLayout.addWidget(self.btnBaseDir, 0, 0, 1, 1)
        self.groupBoxAlphanumeric = QtGui.QGroupBox(Base_LoadThemAll)
        self.groupBoxAlphanumeric.setCheckable(True)
        self.groupBoxAlphanumeric.setChecked(False)
        self.groupBoxAlphanumeric.setObjectName(_fromUtf8("groupBoxAlphanumeric"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBoxAlphanumeric)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_3 = QtGui.QLabel(self.groupBoxAlphanumeric)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.txtFilter = QtGui.QLineEdit(self.groupBoxAlphanumeric)
        self.txtFilter.setObjectName(_fromUtf8("txtFilter"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.txtFilter)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.splitter = QtGui.QSplitter(self.groupBoxAlphanumeric)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.radStarts = QtGui.QRadioButton(self.splitter)
        self.radStarts.setObjectName(_fromUtf8("radStarts"))
        self.radAny = QtGui.QRadioButton(self.splitter)
        self.radAny.setChecked(True)
        self.radAny.setObjectName(_fromUtf8("radAny"))
        self.radEnds = QtGui.QRadioButton(self.splitter)
        self.radEnds.setObjectName(_fromUtf8("radEnds"))
        self.verticalLayout_2.addWidget(self.splitter)
        self.gridLayout.addWidget(self.groupBoxAlphanumeric, 3, 0, 1, 2)
        self.groupBoxBoundingBox = QtGui.QGroupBox(Base_LoadThemAll)
        self.groupBoxBoundingBox.setCheckable(True)
        self.groupBoxBoundingBox.setObjectName(_fromUtf8("groupBoxBoundingBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBoxBoundingBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.txtYMax = QtGui.QLineEdit(self.groupBoxBoundingBox)
        self.txtYMax.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtYMax.setFont(font)
        self.txtYMax.setObjectName(_fromUtf8("txtYMax"))
        self.horizontalLayout_2.addWidget(self.txtYMax)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.txtXMin = QtGui.QLineEdit(self.groupBoxBoundingBox)
        self.txtXMin.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtXMin.setFont(font)
        self.txtXMin.setObjectName(_fromUtf8("txtXMin"))
        self.horizontalLayout.addWidget(self.txtXMin)
        self.txtXMax = QtGui.QLineEdit(self.groupBoxBoundingBox)
        self.txtXMax.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtXMax.setFont(font)
        self.txtXMax.setObjectName(_fromUtf8("txtXMax"))
        self.horizontalLayout.addWidget(self.txtXMax)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.txtYMin = QtGui.QLineEdit(self.groupBoxBoundingBox)
        self.txtYMin.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtYMin.setFont(font)
        self.txtYMin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.txtYMin.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txtYMin.setObjectName(_fromUtf8("txtYMin"))
        self.horizontalLayout_3.addWidget(self.txtYMin)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.splitter_2 = QtGui.QSplitter(self.groupBoxBoundingBox)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.radContains = QtGui.QRadioButton(self.splitter_2)
        self.radContains.setChecked(True)
        self.radContains.setObjectName(_fromUtf8("radContains"))
        self.radIntersects = QtGui.QRadioButton(self.splitter_2)
        self.radIntersects.setObjectName(_fromUtf8("radIntersects"))
        self.btnLoadExtent = QtGui.QPushButton(self.splitter_2)
        self.btnLoadExtent.setObjectName(_fromUtf8("btnLoadExtent"))
        self.verticalLayout.addWidget(self.splitter_2)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBoxBoundingBox, 4, 0, 1, 2)

        self.retranslateUi(Base_LoadThemAll)
        QtCore.QMetaObject.connectSlotsByName(Base_LoadThemAll)

    def retranslateUi(self, Base_LoadThemAll):
        Base_LoadThemAll.setWindowTitle(QtGui.QApplication.translate("Base_LoadThemAll", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Base_LoadThemAll", "Format ", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBaseDir.setToolTip(QtGui.QApplication.translate("Base_LoadThemAll", "Select a base directory", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxAlphanumeric.setTitle(QtGui.QApplication.translate("Base_LoadThemAll", "Alphanumeric filter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Base_LoadThemAll", "Filter string", None, QtGui.QApplication.UnicodeUTF8))
        self.radStarts.setText(QtGui.QApplication.translate("Base_LoadThemAll", "Starts with", None, QtGui.QApplication.UnicodeUTF8))
        self.radAny.setText(QtGui.QApplication.translate("Base_LoadThemAll", "In any position", None, QtGui.QApplication.UnicodeUTF8))
        self.radEnds.setText(QtGui.QApplication.translate("Base_LoadThemAll", "Ends with", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxBoundingBox.setTitle(QtGui.QApplication.translate("Base_LoadThemAll", "Bounding box filter", None, QtGui.QApplication.UnicodeUTF8))
        self.txtYMax.setPlaceholderText(QtGui.QApplication.translate("Base_LoadThemAll", "North", None, QtGui.QApplication.UnicodeUTF8))
        self.txtXMin.setPlaceholderText(QtGui.QApplication.translate("Base_LoadThemAll", "West", None, QtGui.QApplication.UnicodeUTF8))
        self.txtXMax.setPlaceholderText(QtGui.QApplication.translate("Base_LoadThemAll", "East", None, QtGui.QApplication.UnicodeUTF8))
        self.txtYMin.setPlaceholderText(QtGui.QApplication.translate("Base_LoadThemAll", "South", None, QtGui.QApplication.UnicodeUTF8))
        self.radContains.setText(QtGui.QApplication.translate("Base_LoadThemAll", "Contains", None, QtGui.QApplication.UnicodeUTF8))
        self.radIntersects.setText(QtGui.QApplication.translate("Base_LoadThemAll", "Intersects", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLoadExtent.setText(QtGui.QApplication.translate("Base_LoadThemAll", "Map extent", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
