# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_DockWidget.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName(_fromUtf8("DockWidget"))
        DockWidget.resize(337, 449)
        DockWidget.setFloating(False)
        DockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_8 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_8.setContentsMargins(0, 0, 0, -1)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabVector = QtGui.QWidget()
        self.tabVector.setObjectName(_fromUtf8("tabVector"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tabVector)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.scrollArea = QtGui.QScrollArea(self.tabVector)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 319, 427))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.stackedWidgetVector = QtGui.QStackedWidget(self.scrollAreaWidgetContents)
        self.stackedWidgetVector.setMinimumSize(QtCore.QSize(0, 345))
        self.stackedWidgetVector.setObjectName(_fromUtf8("stackedWidgetVector"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.stackedWidgetVector.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.stackedWidgetVector.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stackedWidgetVector, 0, 0, 1, 1)
        self.groupBoxGeometryTypeFilter = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxGeometryTypeFilter.setCheckable(True)
        self.groupBoxGeometryTypeFilter.setChecked(False)
        self.groupBoxGeometryTypeFilter.setObjectName(_fromUtf8("groupBoxGeometryTypeFilter"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBoxGeometryTypeFilter)
        self.gridLayout_2.setContentsMargins(9, 9, -1, 9)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.chkPolygon = QtGui.QCheckBox(self.groupBoxGeometryTypeFilter)
        self.chkPolygon.setObjectName(_fromUtf8("chkPolygon"))
        self.gridLayout_2.addWidget(self.chkPolygon, 0, 3, 1, 1)
        self.chkPoint = QtGui.QCheckBox(self.groupBoxGeometryTypeFilter)
        self.chkPoint.setObjectName(_fromUtf8("chkPoint"))
        self.gridLayout_2.addWidget(self.chkPoint, 0, 1, 1, 1)
        self.chkLine = QtGui.QCheckBox(self.groupBoxGeometryTypeFilter)
        self.chkLine.setObjectName(_fromUtf8("chkLine"))
        self.gridLayout_2.addWidget(self.chkLine, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBoxGeometryTypeFilter, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_6.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabVector, _fromUtf8(""))
        self.tabRaster = QtGui.QWidget()
        self.tabRaster.setObjectName(_fromUtf8("tabRaster"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabRaster)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.scrollArea_2 = QtGui.QScrollArea(self.tabRaster)
        self.scrollArea_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_4 = QtGui.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 319, 455))
        self.scrollAreaWidgetContents_4.setObjectName(_fromUtf8("scrollAreaWidgetContents_4"))
        self.gridLayout_11 = QtGui.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.stackedWidgetRaster = QtGui.QStackedWidget(self.scrollAreaWidgetContents_4)
        self.stackedWidgetRaster.setMinimumSize(QtCore.QSize(0, 345))
        self.stackedWidgetRaster.setObjectName(_fromUtf8("stackedWidgetRaster"))
        self.page_7 = QtGui.QWidget()
        self.page_7.setObjectName(_fromUtf8("page_7"))
        self.stackedWidgetRaster.addWidget(self.page_7)
        self.page_8 = QtGui.QWidget()
        self.page_8.setObjectName(_fromUtf8("page_8"))
        self.stackedWidgetRaster.addWidget(self.page_8)
        self.gridLayout_11.addWidget(self.stackedWidgetRaster, 0, 0, 1, 1)
        self.groupBoxRasterTypeFilter = QtGui.QGroupBox(self.scrollAreaWidgetContents_4)
        self.groupBoxRasterTypeFilter.setCheckable(True)
        self.groupBoxRasterTypeFilter.setChecked(False)
        self.groupBoxRasterTypeFilter.setObjectName(_fromUtf8("groupBoxRasterTypeFilter"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBoxRasterTypeFilter)
        self.gridLayout_10.setContentsMargins(10, 9, -1, 9)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.chkGray = QtGui.QCheckBox(self.groupBoxRasterTypeFilter)
        self.chkGray.setObjectName(_fromUtf8("chkGray"))
        self.gridLayout_10.addWidget(self.chkGray, 0, 0, 1, 1)
        self.chkPalette = QtGui.QCheckBox(self.groupBoxRasterTypeFilter)
        self.chkPalette.setObjectName(_fromUtf8("chkPalette"))
        self.gridLayout_10.addWidget(self.chkPalette, 0, 1, 1, 1)
        self.chkMultiband = QtGui.QCheckBox(self.groupBoxRasterTypeFilter)
        self.chkMultiband.setObjectName(_fromUtf8("chkMultiband"))
        self.gridLayout_10.addWidget(self.chkMultiband, 1, 0, 1, 1)
        self.chkColorLayer = QtGui.QCheckBox(self.groupBoxRasterTypeFilter)
        self.chkColorLayer.setObjectName(_fromUtf8("chkColorLayer"))
        self.gridLayout_10.addWidget(self.chkColorLayer, 1, 1, 1, 1)
        self.gridLayout_11.addWidget(self.groupBoxRasterTypeFilter, 1, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_5.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.tabRaster, _fromUtf8(""))
        self.tabConfiguration = QtGui.QWidget()
        self.tabConfiguration.setObjectName(_fromUtf8("tabConfiguration"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabConfiguration)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setHorizontalSpacing(6)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.scrollArea_3 = QtGui.QScrollArea(self.tabConfiguration)
        self.scrollArea_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName(_fromUtf8("scrollArea_3"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 319, 380))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(15, 9, 9, 9)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.chkGroups = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chkGroups.setMaximumSize(QtCore.QSize(315, 16777215))
        self.chkGroups.setChecked(True)
        self.chkGroups.setObjectName(_fromUtf8("chkGroups"))
        self.verticalLayout_2.addWidget(self.chkGroups)
        self.chkLayersOff = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chkLayersOff.setMaximumSize(QtCore.QSize(315, 16777215))
        self.chkLayersOff.setChecked(True)
        self.chkLayersOff.setObjectName(_fromUtf8("chkLayersOff"))
        self.verticalLayout_2.addWidget(self.chkLayersOff)
        self.chkDoNotEmpty = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chkDoNotEmpty.setChecked(True)
        self.chkDoNotEmpty.setObjectName(_fromUtf8("chkDoNotEmpty"))
        self.verticalLayout_2.addWidget(self.chkDoNotEmpty)
        self.chkIsDoneDialog = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chkIsDoneDialog.setMaximumSize(QtCore.QSize(315, 16777215))
        self.chkIsDoneDialog.setChecked(True)
        self.chkIsDoneDialog.setObjectName(_fromUtf8("chkIsDoneDialog"))
        self.verticalLayout_2.addWidget(self.chkIsDoneDialog)
        self.chkSort = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chkSort.setChecked(True)
        self.chkSort.setObjectName(_fromUtf8("chkSort"))
        self.verticalLayout_2.addWidget(self.chkSort)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem2 = QtGui.QSpacerItem(25, 10, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.chkReverseSort = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chkReverseSort.setObjectName(_fromUtf8("chkReverseSort"))
        self.horizontalLayout_3.addWidget(self.chkReverseSort)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.chkCaseInsensitive = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chkCaseInsensitive.setChecked(True)
        self.chkCaseInsensitive.setObjectName(_fromUtf8("chkCaseInsensitive"))
        self.verticalLayout_2.addWidget(self.chkCaseInsensitive)
        self.chkAccentInsensitive = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chkAccentInsensitive.setChecked(False)
        self.chkAccentInsensitive.setObjectName(_fromUtf8("chkAccentInsensitive"))
        self.verticalLayout_2.addWidget(self.chkAccentInsensitive)
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox.setMaximumSize(QtCore.QSize(315, 80))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.txtNumLayersToConfirm = QtGui.QLineEdit(self.groupBox)
        self.txtNumLayersToConfirm.setMaximumSize(QtCore.QSize(50, 25))
        self.txtNumLayersToConfirm.setObjectName(_fromUtf8("txtNumLayersToConfirm"))
        self.horizontalLayout_2.addWidget(self.txtNumLayersToConfirm)
        self.label_6 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        spacerItem3 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem3)
        self.verticalLayout_2.setStretch(1, 1)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_4.addWidget(self.scrollArea_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabConfiguration, _fromUtf8(""))
        self.tabAbout = QtGui.QWidget()
        self.tabAbout.setObjectName(_fromUtf8("tabAbout"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tabAbout)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.scrollArea_4 = QtGui.QScrollArea(self.tabAbout)
        self.scrollArea_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_4.setLineWidth(1)
        self.scrollArea_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName(_fromUtf8("scrollArea_4"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, -130, 319, 477))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem4 = QtGui.QSpacerItem(20, 15, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.label_4 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_4.setScaledContents(False)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        spacerItem5 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem6, 0, 0, 1, 1)
        self.btnHelp = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        self.btnHelp.setObjectName(_fromUtf8("btnHelp"))
        self.gridLayout_9.addWidget(self.btnHelp, 0, 1, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem7, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_9)
        spacerItem8 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.label_5 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_5.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(_fromUtf8("font:10pt \"Sans Serif\";"))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setOpenExternalLinks(True)
        self.label_5.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        spacerItem9 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_2.setMaximumSize(QtCore.QSize(85, 16777215))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/loadthemall/logo_80x94.png")))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(20, -1, -1, -1)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem10 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem10)
        self.label = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8("font: 8pt \"Sans Serif\";"))
        self.label.setWordWrap(True)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(_fromUtf8("font: 8pt \"Sans Serif\";"))
        self.label_3.setWordWrap(True)
        self.label_3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        spacerItem11 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_3.addItem(spacerItem11)
        self.label_7 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(_fromUtf8("font: 8pt \"Sans Serif\";"))
        self.label_7.setWordWrap(True)
        self.label_7.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_3.addWidget(self.label_7)
        spacerItem12 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem12)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem13 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem13)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_7.addWidget(self.scrollArea_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabAbout, _fromUtf8(""))
        self.gridLayout_8.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem14 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem14)
        self.progressBar = QtGui.QProgressBar(self.dockWidgetContents)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout.addWidget(self.progressBar)
        self.btnLoadLayers = QtGui.QPushButton(self.dockWidgetContents)
        self.btnLoadLayers.setObjectName(_fromUtf8("btnLoadLayers"))
        self.horizontalLayout.addWidget(self.btnLoadLayers)
        spacerItem15 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem15)
        self.gridLayout_8.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        DockWidget.setWindowTitle(_translate("DockWidget", "  Load Them All", None))
        self.groupBoxGeometryTypeFilter.setTitle(_translate("DockWidget", "Geometry type filter", None))
        self.chkPolygon.setText(_translate("DockWidget", "Polygon", None))
        self.chkPoint.setText(_translate("DockWidget", "Point", None))
        self.chkLine.setText(_translate("DockWidget", "Line", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabVector), _translate("DockWidget", "Vector", None))
        self.groupBoxRasterTypeFilter.setTitle(_translate("DockWidget", "Raster type filter", None))
        self.chkGray.setText(_translate("DockWidget", "Gray or Undefined", None))
        self.chkPalette.setText(_translate("DockWidget", "Palette", None))
        self.chkMultiband.setText(_translate("DockWidget", "Multiband", None))
        self.chkColorLayer.setText(_translate("DockWidget", "Color Layer", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRaster), _translate("DockWidget", "Raster", None))
        self.chkGroups.setText(_translate("DockWidget", "Create groups based on directories\' names", None))
        self.chkLayersOff.setText(_translate("DockWidget", "Turn off the loaded layers", None))
        self.chkDoNotEmpty.setText(_translate("DockWidget", "Do not load empty vector layers ", None))
        self.chkIsDoneDialog.setText(_translate("DockWidget", "Show a dialog when the process is done", None))
        self.chkSort.setText(_translate("DockWidget", "Sort loaded layers", None))
        self.chkReverseSort.setText(_translate("DockWidget", "Reverse sort order", None))
        self.chkCaseInsensitive.setText(_translate("DockWidget", "Ignore case in the alphanumeric filter", None))
        self.chkAccentInsensitive.setToolTip(_translate("DockWidget", "This option requires the Python lib \'unidecode\'", None))
        self.chkAccentInsensitive.setText(_translate("DockWidget", "Ignore accents in the alphanumeric filter", None))
        self.txtNumLayersToConfirm.setText(_translate("DockWidget", "50", None))
        self.label_6.setText(_translate("DockWidget", "Number of layers to show you a confirmation dialog before the loading", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabConfiguration), _translate("DockWidget", "Configuration", None))
        self.label_4.setText(_translate("DockWidget", "The <i>Load Them All</i> plugin allows you to load at the same time a number of layers stored in a directory structure, based on a variety of filters you may customize.", None))
        self.btnHelp.setText(_translate("DockWidget", "Help", None))
        self.label_5.setText(_translate("DockWidget", "<html><head/><body><p>Feel free to report bugs, suggest improvements or say hello at gcarrillo@linuxmail.org or directly at the <a href=\"https://github.com/gacarrillor/loadthemall\"><span style=\" text-decoration: underline; color:#0000ff;\">GitHub repository</span></a></p></body></html>", None))
        self.label.setText(_translate("DockWidget", "Copyright (C) 2010-2016 Germán Carrillo", None))
        self.label_3.setText(_translate("DockWidget", "<i>Licensed under the terms of GNU GPL 2</i>", None))
        self.label_7.setText(_translate("DockWidget", "<html><head/><body><p><span style=\" font-style:italic;\">Code contributors:</span><br/><br/>     David Bakeman (v2.1 and v2.4)<br/>     Soeren Gebbert (v2.3)</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAbout), _translate("DockWidget", "About", None))
        self.btnLoadLayers.setText(_translate("DockWidget", "Load layers", None))

import resources_rc
