VECTOR_FORMATS = [
    ("GeoPackage (*.gpkg)", [".gpkg"]),
    ("ESRI Shapefile (*.shp)", [".shp"]),
    ("Mapinfo File (*.mif, *.tab)", [".mif", ".tab"]),
    ("Microstation DGN (*.dgn)", [".dgn"]),
    ("VRT - Virtual Datasource (*.vrt)", [".vrt"]),
    ("Comma Separated Value (*.csv)", [".csv"]),
    ("Geography Markup Language (*.gml)", [".gml"]),
    ("GPX (*.gpx)", [".gpx"]),
    ("KML - Keyhole Markup Language (*.kml, *.kmz)", [".kml", ".kmz"]),
    ("GeoJSON (*.geojson)", [".geojson"]),
    ("GMT (*.gmt)", [".gmt"]),
    ("SQLite (*.sqlite)", [".sqlite"]),
    ("Arc/Info ASCII Coverage (*.e00)", [".e00"]),
    ("AutoCAD DXF (*.dxf)", [".dxf"]),
    ("JSON (*.json)", [".json"]),
]

RASTER_FORMATS = [
    ("Virtual Raster (*.vrt)", [".vrt"]),
    ("GeoTIFF (*.tif, *.tiff)", [".tif", ".tiff"]),
    ("Erdas Imagine Images (*.img)", [".img"]),
    ("Erdas Compressed Wavelets (*.ecw)", [".ecw"]),
    ("ERMapper .ers Labelled (*.ers)", [".ers"]),
    ("DTED Elevation Raster (*.dt)", [".dt2", ".dt3"]),
    ("Arc/Info ASCII Grid (*.asc)", [".asc"]),
    ("Portable Network Graphics (*.png)", [".png"]),
    ("JPEG JFIF (*.jpg, *.jpeg)", [".jpg", ".jpeg"]),
    ("JPEG2000 (*.jp2)", [".jp2"]),
    ("Graphics Interchange Format (*.gif)", [".gif"]),
    ("X11 PixMap Format (*.xpm)", [".xpm"]),
    ("Bitmap image file (*.bmp)", [".bmp"]),
    ("PCIDSK Database File (*.pix)", [".pix"]),
    ("PCRaster Raster File (*.map)", [".map"]),
    ("ILWIS Raster Map (*.mpr, *.mpl)", [".mpr", ".mpl"]),
    ("SRTMHGT File Format (*.hgt)", [".hgt"]),
    ("GMT NetCDF Grid Format (*.nc)", [".nc"]),
    ("GRIdded Binary (*.grb)", [".grb"]),
    ("Idrisi Raster A.1 (*.rst)", [".rst"]),
    ("Golden Software ASCII Grid (*.grd)", [".grd"]),
    ("R Object Data Store (*.rda)", [".rda"]),
    ("Vexcel MFF Raster (*.hdr)", [".hdr"]),
    ("USGS Optional ASCII DEM (*.dem)", [".dem"]),
    ("Magellan topo (*.blx)", [".blx"]),
    ("Rasterlite (*.sqlite)", [".sqlite"]),
    ("SAGA GIS Binary Grid (*.sdat)", [".sdat"]),
    ("Multi-resolution Seamless Image Database (*.sid)", [".sid"]),
    ("BSB Nautical Chart Format (*.kap)", [".kap"]),
]
